name: CI-CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # shallow clone for speed
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Linting Tools
        run: |
          pip install flake8
          cd frontend && npm install && npx install-peerdeps eslint-config-airbnb --dev

      - name: Lint Backend with flake8
        run: flake8 backend/

      - name: Lint Frontend with eslint
        run: cd frontend && npx eslint src/

